Run tests in parallel
Run the tests in parallel using Matrix, also provide a better slack
message on failure and bundle the artifacts together per test.

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -11,9 +11,39 @@ on:
   schedule:
     - cron: "0 23 * * *"
 jobs:
+  set-matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      tests: ${{ steps.select-tests.outputs.tests }}
+    steps:
+      - name: Select Tests
+        id: select-tests
+        run: |
+             if  [[ "${{github.event_name}}" == "schedule"  ]]
+             then
+                   tests='{"tests":[ "teacher-training-adviser", "mailinglist-signup-flow", "homepage-smoke", "event-signup-flow" ]}' 
+             elif  [[ "${{github.event.inputs.application}}" == "APP" ]] 
+             then
+                   tests='{"tests":[ "mailinglist-signup-flow", "homepage-smoke", "event-signup-flow" ]}' 
+             elif  [[ "${{github.event.inputs.application}}" == "TTA"  ]]
+             then
+                   tests='{"tests":[ "teacher-training-adviser"]}' 
+             elif  [[ "${{github.event.inputs.application}}" == "BOTH" ]]
+             then
+                   tests='{"tests":[ "teacher-training-adviser", "mailinglist-signup-flow", "homepage-smoke", "event-signup-flow" ]}' 
+             else
+                   exit 1
+             fi
+             echo ${tests}
+             echo "::set-output name=tests::${tests}"
+
   cypress:
     name: Run Cypress Tests
     runs-on: ubuntu-latest
+    needs: set-matrix
+    strategy:
+      fail-fast: false # doesn't stop other test runs even if one fails
+      matrix: ${{ fromJson(needs.set-matrix.outputs.tests) }}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -21,38 +51,10 @@ jobs:
       - name: Ensure latest version of image
         run:  docker pull dfedigital/dfecypress:latest
         
-      - name:   Run the Tests for Adviser
-        if:  github.event.inputs.application == 'TTA' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH' 
+      - name: Run ${{ matrix.tests }} Test
         run: |
           docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test  dfedigital/dfecypress:latest \
-                             --spec cypress/integration/teacher-training-adviser.spec.js  --headless --browser chrome 
-        env:
-              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
-              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
-        
-      - name:   Run the Tests for Application Mailing List
-        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH'
-        run: |
-             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
-                             --spec cypress/integration/mailinglist-signup-flow.spec.js --headless --browser chrome 
-        env:
-              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
-              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
-        
-      - name:   Run the Tests for Application Event Sign Up
-        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH' 
-        run: |
-             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
-                             --spec cypress/integration/event-signup-flow.spec.js --headless --browser chrome 
-        env:
-              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
-              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
-        
-      - name:   Run the Tests for Application Home Page
-        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH'
-        run: |
-             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
-                             --spec cypress/integration/homepage-smoke.spec.js --headless --browser chrome 
+                             --spec cypress/integration/${{ matrix.tests }}.spec.js --headless --browser chrome 
         env:
               CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
               CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
@@ -61,24 +63,11 @@ jobs:
         uses: actions/upload-artifact@v2
         if: always()
         with:
-          name: Reports
-          path: ./cypress/reports/
-          if-no-files-found: ignore
-
-      - name: Upload video artifact
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Videos
-          path: ./cypress/videos/
-          if-no-files-found: ignore 
-          
-      - name: Upload screenshot artifact
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Screenshots
-          path: ./cypress/screenshots/
+          name: ${{matrix.tests}}
+          path: |
+                ./cypress/reports/
+                ./cypress/videos/
+                ./cypress/screenshots/
           if-no-files-found: ignore
 
       - name: Count Failures
@@ -88,8 +77,20 @@ jobs:
             cat ./cypress/reports/*.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > /tmp/$$.tmp
             if [[ $(cat /tmp/$$.tmp | wc -l) -gt 0  ]]
             then
+                 i=0
+                 echo ::set-output name=adverb::""
+                 while IFS= read -r line
+                 do
+                   if [[ $i -gt 10 ]]
+                   then
+                      echo ::set-output name=adverb::first
+                      break
+                   fi
+                   i=$((i+1))
+                   echo ::set-output name=message${i}::"  - ${line}"
+                 done <  /tmp/$$.tmp
+                 echo ::set-output name=display::${i}
                  echo ::set-output name=number::$(cat /tmp/$$.tmp | wc -l)
-                 echo ::set-output name=errors::"$( cat /tmp/$$.tmp)"
                  exit 1
             fi
             exit 0
@@ -98,12 +99,22 @@ jobs:
         if: failure()
         uses: rtCamp/action-slack-notify@master
         env:
+           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: getintoteaching_tech
            SLACK_COLOR: '#3278BD'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
+           SLACK_TITLE: 'STEVE TEST - Failure running Cypress test ${{ matrix.tests}}'
            SLACK_MESSAGE: |
-                           ${{steps.failures.outputs.number}} Cypress tests have failed
+                           ${{steps.failures.outputs.number}} Cypress tests have failed,
+                           here are the ${{steps.failures.outputs.adverb}} ${{steps.failures.outputs.display}} failures
+                           ${{steps.failures.outputs.message1}}
+                           ${{steps.failures.outputs.message2}}
+                           ${{steps.failures.outputs.message3}}
+                           ${{steps.failures.outputs.message4}}
+                           ${{steps.failures.outputs.message5}}
+                           ${{steps.failures.outputs.message6}}
+                           ${{steps.failures.outputs.message7}}
+                           ${{steps.failures.outputs.message8}}
+                           ${{steps.failures.outputs.message9}}
+                           ${{steps.failures.outputs.message10}}
 
-                           ${{steps.failures.outputs.errors}}
-           SLACK_TITLE: 'Failure: Cypress tests'
-           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
