Update cypress.yml

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -133,8 +133,20 @@ jobs:
 
   Cypress:
     name: ${{github.event.inputs.reference}}
+    if: success()
     runs-on: ubuntu-latest
     needs: RunTests
     steps:
        - name: Check Task has Competed
          run: echo "Test matrix has completed"
+   
+  Failed:
+    name: ${{github.event.inputs.reference}}
+    if:    failure()
+    runs-on: ubuntu-latest
+    needs: RunTests
+    steps:
+       - name: Check Task has Failed
+         run: |
+               echo "Test matrix has failed"
+               exit 1
